export {
  configureMetadataStore,
  defaultMetadataDataDir,
  getConfiguredDataDir,
  resolveMetadataDataDir,
  type MetadataStoreConfig,
} from "./config.js";
export {
  clearAllIndexedData,
  closePreferencesDatabase,
  getAllSessionWorktrees,
  getIndexedSessionsForRepo,
  getPiExecutablePath,
  getPreferences,
  getRegisteredSession,
  getRepoWorktrees,
  getSessionWorktree,
  isRegisteredSession,
  listRegisteredSessionsForRepo,
  recordRepoUsage,
  recordSessionWorktree,
  registerH3CodeSession,
  removeIndexedRepo,
  removeIndexedSession,
  removeRegisteredSession,
  removeSessionWorktreeMapping,
  revealPreferencesDatabase,
  setPiExecutablePath,
  touchRegisteredSession,
  updateDesktopSettings,
  updateRegisteredSessionMetadata,
  type DesktopPreferences,
  type DesktopSettings,
  type IndexedSessionPreference,
  type RecentRepoPreference,
  type RegisterH3CodeSessionInput,
  type RegisteredSessionMetadataPatch,
  type SessionWorktreePreference,
} from "./preferences.js";
