export {
  configureMetadataStore,
  defaultMetadataDataDir,
  getConfiguredDataDir,
  resolveMetadataDataDir,
  type MetadataStoreConfig,
} from "./config.js";
export {
  clearAllIndexedData,
  clearSessionMessageCaches,
  closePreferencesDatabase,
  deleteSessionMessageCache,
  getAllSessionWorktrees,
  getPiExecutablePath,
  getPreferences,
  getRepoWorktrees,
  getSessionMessageCache,
  getSessionWorktree,
  recordRepoSessionRows,
  recordRepoSessions,
  recordRepoUsage,
  recordSessionWorktree,
  removeIndexedRepo,
  removeIndexedSession,
  removeSessionWorktreeMapping,
  revealPreferencesDatabase,
  setPiExecutablePath,
  touchSessionMessageCache,
  updateDesktopSettings,
  upsertSessionMessageCache,
  type DesktopPreferences,
  type DesktopSettings,
  type IndexedSessionPreference,
  type RecentRepoPreference,
  type SessionMessageCacheEntry,
  type SessionMessageCacheState,
  type SessionMessageCacheUpsert,
  type SessionWorktreePreference,
} from "./preferences.js";
