export {
  configureMetadataStore,
  defaultMetadataDataDir,
  getConfiguredDataDir,
  resolveMetadataDataDir,
  type MetadataStoreConfig,
} from "./config.js";
export {
  clearAllIndexedData,
  closePreferencesDatabase,
  getAllSessionWorktrees,
  getPiExecutablePath,
  getPreferences,
  getRepoWorktrees,
  getSessionWorktree,
  recordRepoSessionRows,
  recordRepoSessions,
  recordRepoUsage,
  recordSessionWorktree,
  removeIndexedRepo,
  removeIndexedSession,
  removeSessionWorktreeMapping,
  revealPreferencesDatabase,
  setPiExecutablePath,
  updateDesktopSettings,
  type DesktopPreferences,
  type DesktopSettings,
  type IndexedSessionPreference,
  type RecentRepoPreference,
  type SessionWorktreePreference,
} from "./preferences.js";
